name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Lint code
        run: |
          pip install pylint
          make lint

      - name: Install required packages
        run: |
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          make test

      - name: Build pip package
        run: |
          make pip_pkg
    
      - name: Upload pip package
        uses: actions/upload-artifact@v2
        with:
          name: pip_pkg
          path: ./artifacts/*.whl
      
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: artifacts/
          skip_existing: true

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifacts/
