name: build

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master

jobs:

  build:

    name: Build package
    runs-on: ubuntu-latest

    # container:
    #   image: ghcr.io/mrphys/tensorflow-manylinux:1.0.0

    strategy:
      matrix:
        py_version: [3.8, 3.9]
        # py_version: [3.6, 3.7, 3.8, 3.9]

    env:
      PYTHON: python${{ matrix.py_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Lint code
      #   run: |
      #     make lint PY_VERSION=${{ matrix.py_version }}

      # - name: Compile shared library
      #   run: |
      #     make PY_VERSION=${{ matrix.py_version }}

      # - name: Install required packages
      #   run: |
      #     $PYTHON -m pip install -r requirements.txt

      # - name: Run test suite
      #   run: |
      #     make test PY_VERSION=${{ matrix.py_version }}

      # - name: Build wheel
      #   run: |
      #     make wheel PY_VERSION=${{ matrix.py_version }}

      - name: Build docs
        run: |
          pip install sphinx
          make docs

      # - name: Upload wheel
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: wheels
      #     path: ./artifacts/*.whl

      - name: Upload docs
        if: matrix.py_version == 3.9
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./tools/docs/_build/html
      
      - name: Publish docs to GitHub Pages
        if: matrix.py_version == 3.9
        env:
          USER_NAME: github-actions
          USER_EMAIL: github-actions@github.com

        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git clone --branch docs --single-branch https://github.com/${{ github.repository }}.git ./clone
          mkdir -p docs
          cp -r ./clone/.git ./docs/
          cp -r ./tools/docs/_build/html/* ./docs/
          touch ./docs/.nojekyll
          cd docs
          git add -A
          git commit -m "CI/CD - Update docs"
          git push --force

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: artifacts/
          skip_existing: true

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifacts/
